### ISSUE TITLE
Apache Metrics Dashboard Doesnt appearing

### ISSUE THREAD

**Issue by luancaarvalho** [nikoshet/monitoring-spark-on-docker#1]
Hello, even after the whole proccess finished, the dashboard still with Na fields.
Do i have to put additional configure to grafana and prometheus or just running the docker commands its enought ?
![2020-09-24 15 06 53 localhost 121ffee2293b](https://user-images.githubusercontent.com/34407796/94182581-99049880-fe77-11ea-94a4-c15d2148a19c.png)
Thank you !

**Comment by nikoshet** [comment]
> Hello, even after the whole proccess finished, the dashboard still with Na fields.
> Do i have to put additional configure to grafana and prometheus or just running the docker commands its enought ?
> ![2020-09-24 15 06 53 localhost 121ffee2293b](https://user-images.githubusercontent.com/34407796/94182581-99049880-fe77-11ea-94a4-c15d2148a19c.png)
> Thank you !


Hi, after the following logs the spark application will start running and each metrics will be shown in Grafana.

```
spark            | 240 NameNode
spark            | 818 Worker
spark            | 741 Master
spark            | 599 SecondaryNameNode
spark            | 397 DataNode
spark            | 878 Jps
spark            | /bin/bash: warning: setlocale: LC_ALL: cannot change locale (UTF-8)
spark            | STARTING APP
```

Please run

`
sudo docker-compose down && sudo docker-compose up
`

Then wait for the above logs and on Grafana choose last 5 minutes of metrics to be shown and refresh.

**Comment by nikoshet** [comment]
Closing due to many days of inactivity. If any issues occur, do not hesitate to reopen the thread.
